[package]
name = "fyrox-impl"
version = "0.33.1"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>", "Fyrox Engine Contributors"]
edition = "2021"
license = "MIT"
description = "Feature-rich, easy-to-use, 2D/3D game engine with a scene editor. Like Godot, but in Rust."
keywords = ["sound", "game", "engine", "3d", "gui"]
categories = ["game-engines", "graphics", "gui", "rendering", "wasm"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://fyrox.rs"
documentation = "https://docs.rs/fyrox"
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
rust-version = "1.72"

[dependencies]
fyrox-core-derive = { path = "../fyrox-core-derive", version = "0.22.0" }
fyrox-core = { path = "../fyrox-core", version = "0.27.0", features = ["serde"] }
fyrox-sound = { path = "../fyrox-sound", version = "0.34.0" }
fyrox-ui = { path = "../fyrox-ui", version = "0.24.0" }
fyrox-resource = { path = "../fyrox-resource", version = "0.11.0" }
fyrox-animation = { path = "../fyrox-animation", version = "0.1.0" }
fyrox-graph = { path = "../fyrox-graph", version = "0.1.0" }
rapier2d = { version = "0.18", features = ["debug-render"] }
rapier3d = { version = "0.18", features = ["debug-render"] }
image = { version = "0.24.3", default-features = false, features = ["gif", "jpeg", "png", "tga", "tiff", "bmp"] }
inflate = "0.4.5"
serde = { version = "1", features = ["derive"] }
lazy_static = "1.4.0"
ddsfile = "0.5.0"
rayon = "1.5.1"
tbc = "0.3.0"
bitflags = "2.2.1"
glow = "0.13.1"
walkdir = "2.3.2"
ron = "0.8.0"
fxhash = "0.2.1"
strum = "0.26.1"
strum_macros = "0.26.1"
clap = { version = "4", features = ["derive"] }
winit = { version = "0.29.2", features = ["serde"] }
half = "2.2.1"
fast_image_resize = "3.0.4"
base64 = "0.21.0"
uvgen = "0.1.0"
lightmap = "0.1.1"
libloading = "0.8.1"
serde_json = { version="1.0", optional=true }
gltf = { version = "1.4.0", optional = true, default-features = false, features = ["names", "utils"] }

# This dependency isn't actually used by the engine, but it is needed to prevent cargo from rebuilding
# the engine lib on different packages.
hashbrown = { version = "0.14.3", features = ["raw"] }

[features]
enable_profiler = ["fyrox-core/enable_profiler"]
gltf_blend_shapes = ["gltf", "gltf/extras", "dep:serde_json"]
mesh_analysis = []

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.31"
glutin-winit = "0.4.2"
raw-window-handle = "0.5.0"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.29.2", features = ["android-native-activity"] }