[package]
name = "fyrox-build-tools"
version = "0.36.0"
edition = "2021"

[dependencies]
fyrox-core = { path = "../fyrox-core", version = "0.36.0" }
serde = { version = "1.0.215", features = ["derive"] }