[package]
name = "fyrox-gpu-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox-core = { path = "../fyrox-core", version = "0.28.1" }
fxhash = "0.2.1"
glow = "0.14.0"
bytemuck = "1.16.1"
serde = "1"
strum = "0.26.3"
strum_macros = "0.26.4"